CREATE TABLE  Student (

FIRST_NAME  CHAR  NOT NULL,
LAST_NAME  CHAR,
AGE  INTEGER, 
CITY CHAR

);


INSERT  INTO Student VALUES ("Adiya", "HOORA", 22, "BANGLORE");
INSERT  INTO Student VALUES ("SUZIE", " CHANDRA", 18, "SIKKIM");
